package feature // this is the package name 
        feature // this is the namespace prefix
        "http://org.owltext/feature" // the namespace URI 
	{

	abstract class Feature {
		attribute EString name (1..1);
		containment reference Feature children (0..-1) opposite parent;
		reference Feature parent (0..1) opposite children;
	}
	
	class MandatoryFeature extends Feature {
	}
	
	class OptionalFeature extends Feature {
	}

}